### ISSUE TITLE
Transfer is not filtrered while exporting and filter for agencies

### ISSUE THREAD

**Issue by Josef-A** [afimb/gtfslib-python#50] opened 2016-11-11 14:39 UTC
Hi,

Maybe I misunderstood how to formulate filtering. I run the export plugin with --filter="Agency.agency_name=='SL'" as parameter.

The resulted GTFS is not valid since there are transfers where the corresponding stops is not defined.

Regards
       Josef Andersson

**Comment by laurentg** [comment] 2016-11-13 16:53
I confirm the issue. The problem lies again in the auto-joining mechanism. This should be easier to solve than the problem with the fares though, I'll try to come up with a fix soon.

**Comment by laurentg** [comment] 2016-11-14 15:26
The problem is more complex than I though. The support for filtering in the GTFS export plugin has never been fully tested and is currently buggy. The problem with filtering each object is that the semantics are not always the same between a GTFS export and the common sense. For example filtering stops on Route or Agency will list all stops from all stop_times; but this is not enough for a GTFS export as one need the parent station too. Joining on the parent station for the DAO would be brain-dead though.

The proper solution is to only use the provided filter for basic classes of object (agencies, routes, trips, stop times, stops, calendar, calendar_dates) and deriving the proper filter for the other objects based on the previous returned object lists (stop > parent stations, stops+stations > transfers, zones+routes > fares_attributes > fare_rules, etc...)

**Comment by laurentg** [comment] 2016-11-14 15:35
Closing this issue, see #51.

**Comment by laurentg** [comment] 2016-11-14 17:32
This issue should be solved now, could you re-test with your data?

**Comment by Josef-A** [comment] 2016-11-15 11:39
Nearly there!

I updated gtfslib and rerun. Then I sorted the transfer.txt files from the run and from my previous fix. Then I could compare them. The only difference is that some transfer lines are repeated. See line 4 and 6 below for example.

from_stop_id	to_stop_id	transfer_type	min_transfer_time
7400001	7400001	2	1200
7400001	7400622	2	1200
7400001	7400622	2	1200
7400001	7401541	2	1500
7400001	7401541	2	1500
7400001	7404383	2	1200

**Comment by laurentg** [comment] 2016-11-15 18:25
Indeed there is a problem, since we use grouping we can end up with duplicates for large number of transfers. Correction in process.

**Closed** 2016-11-15 18:26 UTC

**Comment by laurentg** [comment] 2016-11-15 18:38
@Josef-A Let's hope is really solved now, can you re-test with your data?

**Comment by Josef-A** [comment] 2016-11-16 09:08
Now it's working.

I had a small problem. See issue #53. 

I get identical result as my workaround.
Thanks a lot for all fast fixes.
